name: programovil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8

  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

  http: ^1.6.0
  flutter_dotenv: ^5.1.0
  iconsax: ^0.0.8
  provider: ^6.1.5+1
  google_generative_ai: ^0.4.7

  pdf: ^3.10.8
  printing: ^5.12.0

  universal_html: ^2.2.4
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^11.3.1

  excel: ^2.1.0
  csv: ^5.0.2
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^2.8.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/platos/
    - assets/images/ingredientes/
    - assets/animations/
    - assets/videos/
    - assets/images/fondo.webp
    - .env
    - assets/images/jaguar_cocinero.png
    - assets/images/vegetables_botton.png
    - assets/images/banner_home.png
    - assets/images/yagu_reportes.png